### ISSUE TITLE
Shuting ebooks unorthodoxly

### ISSUE THREAD

**Issue by Coalms** [mtshrmn/nuber#1]
Dunno if you or anyone else thinks this is a problem but shuting down a book with ctrl+c or shuting the window itself won't save current progress

Understanding that saving in every keystroke is infact bloat I'd like to propose savestates to happen in page flipping as well not just when pressing q,this would mitigate the problem of forgeting your last read chapter or having to travel accros multiple pages when reading lots of diffrent books but still not causing unecessery resource usage(if it happens at all)when going up and down a page

to summerize I think it wourld be cool to save on q h and l keystrokes and if not resource heavy ok j and k as well

(PS Seriously I love this e-reader thanks for your effort and Id do a commit myself to help out here if I knew rust at all)

**Comment by mtshrmn** [comment]
I think this is a great suggestion, I would also add saving on ctrl-c and SIGKILL.

I have more features I'd like to add first but I just can't find the time to work on them (I should really open issues for them). I can't promise I'll be able to implement it any time soon. 

By the way, everything related to the reader itself (curses) is written in python, only the heavy lifting is written in rust.

**Comment by mtshrmn** [comment]
Implemented in https://github.com/mtshrmn/nuber/commit/209217e381b723cfc5cc41948e5f820041811b18
